services:
  mssql:
    container_name: TodoList
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
       - ./init:/docker-entrypoint-initdb.d
    environment:
      SA_PASSWORD: "Tod0List!"
      ACCEPT_EULA: "Y"